#!/bin/bash

echo "> cd $(dirname "$0")/.."
cd $(dirname "$0")/..

if [ ! -d install ]; then
  echo "> mkdir -p install"
  mkdir -p install/include
fi

if [ ! -d 3rdparty ]; then
  echo "> mkdir -p 3rdparty"
  mkdir -p 3rdparty
fi

echo "> cd 3rdparty"
cd 3rdparty

echo "> git config --global advice.detachedHead false"
git config --global advice.detachedHead false

if [ ! -d libnoise2d ]; then
  echo "> git clone --branch v1.2.1 --depth 1 https://github.com/planeworld/libnoise2d.git"
  git clone --branch v1.2.1 --depth 1 https://github.com/planeworld/libnoise2d.git
fi

if [ ! -d box2d ]; then
  echo "> git clone --branch v2.4.1 --depth 1 https://github.com/erincatto/box2d.git"
  git clone --branch v2.4.1 --depth 1 https://github.com/erincatto/box2d.git
fi

if [ ! -d entt ]; then
  echo "> git clone --branch v3.10.3 --depth 1 https://github.com/skypjack/entt.git"
  git clone --branch v3.10.3 --depth 1 https://github.com/skypjack/entt.git
fi

if [ ! -d corrade ]; then
  echo "> git clone --branch v2020.06 --depth 1 https://github.com/mosra/corrade.git"
  git clone --branch v2020.06 --depth 1 https://github.com/mosra/corrade.git
fi

if [ ! -d magnum ]; then
  echo "> git clone --branch v2020.06 --depth 1 https://github.com/mosra/magnum.git"
  git clone --branch v2020.06 --depth 1 https://github.com/mosra/magnum.git
fi

if [ ! -d imgui ]; then
  echo "> git clone --branch v1.79 --depth 1 https://github.com/ocornut/imgui.git"
  git clone --branch v1.79 --depth 1 https://github.com/ocornut/imgui.git
fi

if [ ! -d magnum-integration ]; then
  echo "> git clone --branch v2020.06 --depth 1 https://github.com/mosra/magnum-integration.git"
  git clone --branch v2020.06 --depth 1 https://github.com/mosra/magnum-integration.git
fi


# Install libnoise2d

if [ ! -d ../install/libnoise2d ]; then
  echo "> cd libnoise2d"
  cd libnoise2d
  echo "> mkdir -p build"
  mkdir -p build
  echo "> cd build"
  cd build
  echo "> cmake .. -DCMAKE_INSTALL_PREFIX=../../../install -DUSE_XXHASH=ON -DCMAKE_BUILD_TYPE=RELEASE"
  cmake .. -DCMAKE_INSTALL_PREFIX=../../../install -DUSE_XXHASH=ON -DCMAKE_BUILD_TYPE=RELEASE
  echo "> make -j8 install"
  make -j8 install
  echo "> cd ../.."
  cd ../..
fi

# Install box2d

if [ ! -d ../install/box2d ]; then
  echo "> cd box2d"
  cd box2d
  echo "> mkdir -p build"
  mkdir -p build
  echo "> cd build"
  cd build
  echo "> cmake .. -DCMAKE_INSTALL_PREFIX=../../../install -DBOX2D_BUILD_TESTBED=OFF -DBOX2D_BUILD_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=RELEASE"
  cmake .. -DCMAKE_INSTALL_PREFIX=../../../install -DBOX2D_BUILD_TESTBED=OFF -DBOX2D_BUILD_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=RELEASE
  echo "> make -j8 install"
  make -j8 install
  echo "> cd ../.."
  cd ../..
fi

# Install entt

if [ ! -d ../install/entt ]; then
  echo "> cd entt"
  cd entt

  if [ ! -d build ]; then
    echo "> mkdir -p build"
    mkdir -p build
  fi

  echo "> cd build"
  cd build
  echo "> cmake .. -DCMAKE_INSTALL_PREFIX=../../../install -DBUILD_GMOCK=OFF -DBUILD_TESTING=OFF -DINSTALL_GTEST=OFF -DCMAKE_BUILD_TYPE=RELEASE"
  cmake .. -DCMAKE_INSTALL_PREFIX=../../../install -DBUILD_GMOCK=OFF -DBUILD_TESTING=OFF -DINSTALL_GTEST=OFF -DCMAKE_BUILD_TYPE=RELEASE
  echo "> make -j8 install"
  make -j8 install
  echo "> cd ../.."
  cd ../..
fi

# Install corrade
if [ ! -d ../install/Corrade ]; then
  echo "> cd corrade"
  cd corrade
  echo "> mkdir -p build"
  mkdir -p build
  echo "> cd build"
  cd build
  echo "> cmake .. -DCMAKE_PREFIX_PATH=../../../install -DCMAKE_INSTALL_PREFIX=../../../install -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DEPRECATED=OFF"
  cmake .. -DCMAKE_PREFIX_PATH=../../../install -DCMAKE_INSTALL_PREFIX=../../../install -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DEPRECATED=OFF
  echo "> make -j8 install"
  make -j8 install
  echo "> cd ../.."
  cd ../..
fi

# Install magnum
if [ ! -d ../install/Magnum ]; then
  echo "> cd magnum"
  cd magnum
  echo "> mkdir -p build"
  mkdir -p build
  echo "> cd build"
  cd build
  echo "> cmake .. -DCMAKE_PREFIX_PATH=../../../install -DCMAKE_INSTALL_PREFIX=../../../install -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DEPRECATED=OFF -DWITH_DEBUGTOOLS=ON -DWITH_SDL2APPLICATION=ON"
  cmake .. -DCMAKE_PREFIX_PATH=../../../install -DCMAKE_INSTALL_PREFIX=../../../install -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DEPRECATED=OFF -DWITH_DEBUGTOOLS=ON -DWITH_SDL2APPLICATION=ON
  echo "> make -j8 install"
  make -j8 install
  echo "> cd ../.."
  cd ../..
fi

# Install imgui
if [ ! -d ../install/imgui ]; then
  echo "> cd imgui"
  cd imgui
  echo "> cp *.h ../../install/include/"
  cp *.h ../../install/include/
  echo "> cp *.cpp ../../install/include/"
  cp *.cpp ../../install/include/
  echo "> cd .."
  cd ..
fi

# Install magnum-integration
if [ ! -d ../install/MagnumIntegration ]; then
  echo "> cd magnum-integration"
  cd magnum-integration
  echo "> mkdir -p build"
  mkdir -p build
  echo "> cd build"
  cd build
  echo "> cmake .. -DCMAKE_PREFIX_PATH=../../../install -DCMAKE_INSTALL_PREFIX=../../../install -DCMAKE_BUILD_TYPE=RELEASE -DWITH_IMGUI=ON -Dimgui_DIR=../../install"
  cmake .. -DCMAKE_PREFIX_PATH=../../../install -DCMAKE_INSTALL_PREFIX=../../../install -DCMAKE_BUILD_TYPE=RELEASE -DWITH_IMGUI=ON -Dimgui_DIR=../../install
  echo "> make -j8 install"
  make -j8 install
  echo "> cd ../.."
  cd ../..
fi

# Add modules
if [ ! -d modules ]; then
  echo "> mkdir -p modules"
  mkdir -p modules
  echo "> cp magnum-integration/modules/* modules/"
  cp magnum-integration/modules/* modules/
  echo "> cd .."
  cd ..
fi

# Install sol release
if [ ! -d install/include/sol ]; then
  cd install/include/
  wget --no-clobber https://github.com/ThePhD/sol2/releases/download/v3.3.0/sol.hpp
  mkdir sol
  cd sol
  wget --no-clobber https://github.com/ThePhD/sol2/releases/download/v3.3.0/config.hpp
  wget --no-clobber https://github.com/ThePhD/sol2/releases/download/v3.3.0/forward.hpp
  cd ../../..
fi
